### ISSUE TITLE
UUID values not being JSON serialized properly

### ISSUE THREAD

**Issue by kauberry** [pacifica/pacifica-metadata#225]
### Pacifica Metadata version
Metadata v0.10.1

### Pacifica Core Software versions
Pacifica 1.0b

### Platform Details
MyEMSL

### Scenario:
New UUID values that are being used in mapping objects (ProjectUsers, InstrumentUser, etc.) are not currently JSON serializable when retrieving a hashlist for an object from the objectinfo endpoint. This is affecting the performance of the EUS synchronization script.

### Steps to Reproduce:
Issue a GET request to the "/objectinfo/project_user/hashlist" endpoint.

### Expected Result:
You should get a list of hash values for the records and a 200.
Output should look more like this... (abbreviated)

```json
{
  "hash_list": [
    "920b520197c9be9968ac22238bff61fd",
    "328c2269f800b5b6094ff06766f227d4",
    "a2f5d9c1322a3a366e010afba2e07df8",
    "1dd4b12ba58a35fa64b98279b01187db",
    "9e9ff8fa8f2fc59634b3aa1349ccdaeb",
    "576e4b4d508ed41a5b7d00416f1c275e"
  ],
  "hash_lookup": {
    "920b520197c9be9968ac22238bff61fd": {
      "key_list": {
        "uuid": "ee6f9acd-3223-4831-8900-51cf00db1871"
      },
      "index_hash": "920b520197c9be9968ac22238bff61fd"
    },
    "328c2269f800b5b6094ff06766f227d4": {
      "key_list": {
        "uuid": "b89ac981-c985-4535-a6c5-ac87cbd1e59a"
      },
      "index_hash": "328c2269f800b5b6094ff06766f227d4"
    },
    "a2f5d9c1322a3a366e010afba2e07df8": {
      "key_list": {
        "uuid": "2824d8c0-7b03-4545-91c0-7722622bfb08"
      },
      "index_hash": "a2f5d9c1322a3a366e010afba2e07df8"
    },
    "1dd4b12ba58a35fa64b98279b01187db": {
      "key_list": {
        "uuid": "399c21ed-610c-47ff-bfae-7b5662bbde63"
      },
      "index_hash": "1dd4b12ba58a35fa64b98279b01187db"
    },
    "9e9ff8fa8f2fc59634b3aa1349ccdaeb": {
      "key_list": {
        "uuid": "d0a9283a-5e2e-49cd-946a-a6d5cff49e8b"
      },
      "index_hash": "9e9ff8fa8f2fc59634b3aa1349ccdaeb"
    },
    "576e4b4d508ed41a5b7d00416f1c275e": {
      "key_list": {
        "uuid": "f4cc5de0-b7b6-42b2-9214-f79010093aff"
      },
      "index_hash": "576e4b4d508ed41a5b7d00416f1c275e"
    }
  }
}
```

### Actual Result:
What you actually get is a 500 with the message...

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 692, in _do_respond
    response.finalize()
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 888, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 846, in collapse_body
    new_body = b''.join(self.body)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_json.py", line 24, in encode
    for chunk in _encode(value):
  File "/usr/local/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'UUID' is not JSON serializable
```

**Comment by dmlb2000** [comment]
@kauberry the url you posted isn't parsing for me did you mean `{0}/objectinfo?object_class_name=ProjectUser&operation=hashlist`?

**Comment by kauberry** [comment]
Here's the full url for one that works (no UUID's)
https://metadata.my.emsl.pnl.gov//objectinfo/users/hashlist

This one is for the broken one
https://metadata.my.emsl.pnl.gov//objectinfo/project_user/hashlist

It gives me a 500 error, since it's broken. =)

**Comment by dmlb2000** [comment]
@kauberry Got it, CherryPy is helping and we only have tests in the one form not both...
